### ISSUE TITLE
PHP version?

### ISSUE THREAD

**Issue by bmaziere** [ekino/sonata#1]
As this project will be used on new project, think we should only support php 7.
Is there any constraint to set a minimal version to 7.1?

**Comment by nanofelis** [comment]
Given we build additionnal features for sonata shouldn't we follow the same constraints ? 

for instance sonata core requires the following  
````
requires
cocur/slugify ^1.4 || ^2.0 || ^3.0
php ^5.6 || ^7.0
sonata-project/datagrid-bundle ^2.0
symfony/config ^2.8 || ^3.2 || ^4.0
symfony/form ^2.8 || ^3.2 || ^4.0
symfony/framework-bundle ^2.8 || ^3.2 || ^4.0
symfony/http-foundation ^2.8 || ^3.2 || ^4.0
symfony/property-access ^2.8 || ^3.2 || ^4.0
symfony/security ^2.8 || ^3.2 || ^4.0
symfony/translation ^2.8 || ^3.2 || ^4.0
symfony/twig-bridge ^2.8 || ^3.2 || ^4.0
symfony/validator ^2.8 || ^3.2 || ^4.0
twig/extensions ^1.5
twig/twig ^1.34 || ^2.0
````

**Comment by Wharenn** [comment]
PHP 5.6 is deprecated and security support is ending in december. I think this initiative should support the move of projects to PHP7 by not dealing with deprecations.

**Comment by bmaziere** [comment]
Then, does everybody agrees with minimum requirement set to php7.1?
