### ISSUE TITLE
What should be our policy on merging?

### ISSUE THREAD

**Issue by bmaziere** [ekino/sonata#10]
- How many approvements from reviewers is required for a merge? 

👍  : 2
❤️  : 3
🎉  : 4
✨  : 5
🚌  : 6

Let's vote :)

**Comment by bdejacobet** [comment]
❤️

**Comment by mremi** [comment]
3 👍looks good to me

**Comment by srascar** [comment]
4 👍 : for absolute majority

**Comment by bmaziere** [comment]
ok as 5 ❤️  is the majority, merge requests will be accepted after 3 approvals from reviewers
if everybody is very reactive, we may go to 4
Will add this decision to the contributing policy
Closing this one
