### ISSUE TITLE
Base functionalities this repo should contain

### ISSUE THREAD

**Issue by bmaziere** [ekino/sonata#3]
This issue is raised to discuss about functionalities that should be included into that repository. Feel free to comment and add what you saw in your past projects that could be useful and reusable.
First thoughts:
- Entities & admin for menu (should be enabled by configuration)
- Block & page translatable (abstract + trait)
- Field media builder helper for block and fragment (trait)
- Flush block cache helper (trait)
- El Duplicator
- Entities field translatable (trait)
- CaseInsensitiveStringFilter
- Helper for testing admin & block & fragment (trait)
...

**Comment by bdejacobet** [comment]
- InternalExternalLink form type (admin menu item can use it)

**Comment by srascar** [comment]
Could you detail what each of these form is doing ?

**Comment by srascar** [comment]
* AdminFormFieldTestTrait.php -  Contains 2 methods:
  * mockFormMapper(AdminInterface $admin) - Create a mock of the form mapper that stores all added fields in a public property fields (it also skips the groups)
`$formMapper->fields[] = [$name, $type, $config];`
  * expectInOrder($formMapper, array $fields) - Receive a formMapper mock and a list of fields to check (internally calls the `configureFormFields` function of the admin
* FormFieldTestTrait - Similar to AdminFormFieldTestTrait but for the fragments (1 method only)
It needs to be renamed into `FragmentFieldTestTrait` and add `FragmentService` as 1st parameter.
  * expectInOrder(array $fields, Fragment $fragment = null)

**Comment by nanofelis** [comment]
* Pages and articles routing helplers (+ twig extensions)

**Comment by srascar** [comment]
@bdejacobet zoning is really cool. Could we just rename it into `ImmutableMatrixType`
@nanofelis Good one. But I'm pretty sure we can make it generic. We should add the `RoutingHelperExtension` instead of the classes themselve

**Comment by nanofelis** [comment]
* Allow fixed sonata form id for behat test (cf @Wharenn & @bdejacobet works on Canal)

**Comment by bmaziere** [comment]
closing this one. We will now open one issue by functionality that should be include in that repo. thx all!
